
(define (problem blocks-00)
(:domain Blocks)
(:objects slot1 - slot slot2 - slot slot3 - slot block01 - block block02 - block block03 - block)
(:init
(= (total-cost) 0)
(on block02 slot3)
(clear block02)
(on block01 slot2)
(clear block03)
(clear block01)
(handempty)
(on block03 slot1))
(:goal (and (on block01 block02)
(clear slot2)
(on block02 block03)
(clear block01)
(handempty)
(clear slot3)
(on block03 slot1)))
(:metric minimize (total-cost)))
