
(define (problem blocks-00)
(:domain Blocks)
(:objects slot1 - slot slot2 - slot slot3 - slot block01 - block block02 - block block03 - block)
(:init
(= (total-cost) 0)
(clear slot1)
(handempty)
(on block01 slot3)
(clear block02)
(on block03 slot2)
(clear block01)
(on block02 block03))
(:goal (and (on block03 slot3)
(clear slot1)
(handempty)
(clear block02)
(clear block01)
(on block01 slot2)
(on block02 block03)))
(:metric minimize (total-cost)))
