
(define (problem elevator-00)
(:domain Elevator)
(:objects floor1 - floor floor2 - floor floor3 - floor floor4 - floor passenger01 - passenger passenger02 - passenger passenger03 - passenger passenger04 - passenger)
(:init
(= (total-cost) 0)
(origin passenger04 floor3)
(destin passenger02 floor2)
(origin passenger03 floor1)
(above floor2 floor3)
(destin passenger04 floor1)
(origin passenger01 floor1)
(lift-at floor1)
(destin passenger01 floor1)
(above floor1 floor2)
(origin passenger02 floor3)
(destin passenger03 floor3)
(above floor3 floor4))
(:goal (and (origin passenger04 floor3)
(destin passenger02 floor2)
(served passenger01)
(origin passenger03 floor1)
(served passenger04)
(above floor2 floor3)
(served passenger02)
(destin passenger04 floor1)
(origin passenger01 floor1)
(destin passenger01 floor1)
(above floor1 floor2)
(origin passenger02 floor3)
(destin passenger03 floor3)
(above floor3 floor4)
(served passenger03)))
(:metric minimize (total-cost)))
