
(define (problem blocks-00)
(:domain Blocks)
(:objects slot1 - slot slot2 - slot slot3 - slot block01 - block block02 - block block03 - block)
(:init
(= (total-cost) 0)
(on block01 block02)
(clear slot3)
(on block02 block03)
(clear slot1)
(handempty)
(clear block01)
(on block03 slot2))
(:goal (and (on block01 slot3)
(handempty)
(clear block01)
(on block02 slot1)
(clear block02)
(clear block03)
(on block03 slot2)))
(:metric minimize (total-cost)))
