
(define (problem elevator-00)
(:domain Elevator)
(:objects floor1 - floor floor2 - floor floor3 - floor floor4 - floor passenger01 - passenger passenger02 - passenger passenger03 - passenger)
(:init
(= (total-cost) 0)
(above floor3 floor4)
(origin passenger02 floor2)
(destin passenger03 floor4)
(origin passenger03 floor2)
(above floor1 floor2)
(lift-at floor1)
(destin passenger01 floor4)
(origin passenger01 floor3)
(above floor2 floor3)
(destin passenger02 floor1))
(:goal (and (above floor3 floor4)
(origin passenger02 floor2)
(destin passenger03 floor4)
(origin passenger03 floor2)
(above floor1 floor2)
(served passenger01)
(destin passenger01 floor4)
(served passenger02)
(origin passenger01 floor3)
(above floor2 floor3)
(served passenger03)
(destin passenger02 floor1)))
(:metric minimize (total-cost)))
